src/dct/Theater.lua

To avoid losing the old state file before the new state file is ready
move to a write new rename model so that we are all but guaranteed we
have a new state file before attempting to delete the old one. This is
done by using os.rename which on most filesystems is an atomic operation
and usually cannot fail barring hardware failure.

theater: write then rename state file

---

.luacheckrc
Makefile
hooks/dct-hook.lua
mission/dct-mission-init.lua
src/dct.lua
src/dct/Command.lua
src/dct/Theater.lua
src/dct/ai/Commander.lua
src/dct/ai/Mission.lua
src/dct/assets/AssetBase.lua
src/dct/assets/AssetManager.lua
src/dct/assets/Player.lua
src/dct/assets/StaticAsset.lua
src/dct/init.lua
src/dct/libs/Observable.lua
src/dct/systems/loadouts.lua
src/dct/templates/STM.lua
src/dct/ui/cmds.lua
src/dct/ui/groupmenu.lua
tests/runtests
tests/test-0003-class.lua
tests/test-all-templates.lua
tests/test-events.lua
tests/test-init.lua
tests/test-theater.lua
tests/test-ui-cmds.lua
tests/test-ui-cmds2.lua
tests/test-ui-groupmenu.lua

Miscellaneous changes to facilitate squadrons feature. We change the Theater class to be a singleton, delay the spawning of assets, and stop passing a theater reference everywhere.
The delaying of spawning assets allows the Theater class constructor to complete so that we have an instance of the Theater class to reference when assets are spawned. This is important when "generator" assets generate and spawn additional assets in their spawn function.
We no longer need to pass a reference to the theater class everywhere as now the Theater class is a singleton and just calling Theater.singleton() will simply give us the same global object.

Theater cleanup

---

data/mission/theater/region1/base-defense/BandarEJaskAirbaseDefence.dct
doc/03-designer.md
src/dct/assets/AssetBase.lua
src/dct/assets/StaticAsset.lua
src/dct/templates/Template.lua

Define a new template attribute `regenerate` that when `true` will cause the
given asset to lookup the template it was based off of and copy over the
`tpldata` again.
Currently only StaticAssets comply with this setting as no other assets
utilize tpldata in any meaningful way.
Closes: #117

template: allow some assets to regenerate

---

src/dct/settings/theater.lua

Removed harrier from gridfmt list, as it should be DMS not DDM.

Fix harrier coord type

---

src/dct/ui/cmds.lua

Minor change to create target markers to players that join an ongoing mission, which is currently only visible to the player which originally requested it.
Test done by requesting a mission from slot A, noting the marker created by DCT, switching to slot B, noting the marker is not available in the new slot, and then joining the mission via A's mission code, which now creates a marker for slot B.

Feature: add map marker for player when joining a mission

---

src/dct/Theater.lua
src/dct/systems/bldgPersist.lua
src/dct/systems/tickets.lua
src/dct/ui/scratchpad.lua

This changes how systems register with the theater to a component object
model. Making common how one accesses an instance of a system in the
theater and registering a system with the theater. This also forces
a common API that each system must provide:
* must be a class and the init accepts a single argument, an instance
of the theater
* if the system needs to save state it just needs to implement the
Marshallable interface
Finally this change removes the pollution of the Theater with individual
member objects, they are now all contained under `Theater.systems`.

systems: rework how systems register with theater

---

src/dct/libs/Timer.lua
tests/test-0005-timer.lua

This count up timer takes the timeout and will count the amount of time
elapsed since the last call to update(). Once elapsed time is greater
than timeout the timer has expired. The timer notes the current time
using timefunc and then takes the difference between the last time
and the current time to figure out the elapsed time since the last
call to update().
This timer does not handle roll overs of the underlying timefunc.

libs: implement a generic timer class

---

src/dct/Theater.lua
src/dct/assets/StaticAsset.lua
src/dct/systems/bldgPersist.lua

Also, change the storage of scenery ids to be a set instead of a list.
Closes: #149

systems: while restoring state ignore scenery events

---

src/dct/utils.lua

The correct spelling was verified by extracting the theatre file from a .miz that uses the map

Fix spelling of Caucasus in timezone table

---

src/dct/ai/Commander.lua
src/dct/ai/Mission.lua
src/dct/assets/Player.lua
src/dct/enum.lua
src/dct/settings/server.lua

When a player leaves a slot start a timer if the slot is assigned to a mission. Upon the expiration of the timer remove the slot from the assigned mission. Allow the server administrator the ability to adjust when empty slots should expire from an assigned mission. To preserve previous behaviour slot expiration is left off and slots will be removed when the mission expires. It is up to the administrator to setup a shorter slot expiration.

Feature slot expire

---

src/dct/Theater.lua

Add a version to the state file. That way if we update the code that
breaks older state files we can just change this version and old
state files will automatically be ignored.

theater: version state files

---

src/dct/settings/theater.lua
src/dct/systems/loadouts.lua
src/dct/templates/STM.lua

DCS changed how routes were stored in stm files. Now if a route does not
have a name there is no name entry in the route entry. So we need to
allow for receiving a nil name.

template: route names do not always exist

---

src/dct/settings/theater.lua
src/dct/systems/loadouts.lua

For loadout restrictions the weapon type name (typeName) should be used
instead of the display name as the display name can change depending on
internationalization and for other reasons. The type name should be the
fixed name that never changes.

loadouts: reference weapon type name

---

hooks/dct-hook.lua
src/dct/Theater.lua
src/dct/assets/Airbase.lua
src/dct/assets/AssetManager.lua
src/dct/assets/StaticAsset.lua
src/dct/enum.lua
src/dct/libs/kickinfo.lua
src/dct/templates/Template.lua
src/dcttestlibs/dcsstubs.lua

Some FARPs do not emmit takeoff or landing events. This attempts to
detect if a FARP is within a defined radius and amends the event object
to include the airbase.

theater: fixup land/takeoff events

---

hooks/dct-hook.lua
src/dct/enum.lua
src/dct/libs/kickinfo.lua

The enum.lua file has grown and references symbols not available in the
hooks environment. Break out from the enum.lua the specific additions to
the enum.lua that are also needed in hooks and reference this specific
file in the hooks script.
Closes: #189

hooks: fix require of enum

---

src/dct/Theater.lua
src/dct/systems/loadouts.lua
src/dct/ui/groupmenu.lua
tests/test-ui-cmds2.lua

missionCommands.addMenu accepts multiple user arguments to the handler
function, however, it seems that behavior is not documented, and the
extra parameters can cause memory corruption under certain circumstances
when running queued commands on units that have been removed by the slot
kicker. By reducing the user arguments to one, the functions behave
correctly and DCS doesn't crash anymore when calling them. The
theater object used to be passed in the commands, but now it is injected
directly into the playerRequest method via the singleton call (as it was
done in groupmenu.lua before).

groupmenu: fix crash caused under specific circumstances

---

src/dct/ui/cmds.lua

This change was missed during the initial refactor of how systems
register with the theater. This will restor functionality of the
scratchpad.
Fixes: 02827edee955 ("systems: rework how systems register with theater")

scratchpad: fix latent bug after system rework

---

src/dct/systems/weaponstracking.lua

It seems some weapons do not have warhead tables and results in the
following error:
[string "C:\Users\hoggit\Saved Games\DCS.openbeta_server\Mods\tech\DCT\lua\dct\systems\weaponstracking.lua"]:29: attempt to index field 'warhead' (a nil value)
The solution is to just ignore those weapon entries that are missing
warhead tables.

systems: fix error in weaponstracking

---

src/dct/assets/AssetManager.lua
src/dct/assets/Player.lua

Player assets are special and the code assumes they are never deleted.
They also utilize setting the dead flag to emit a DCT asset dead event
so that ticket accounting is done properly. This unfortunately makes
Player assets look dead to the rest of the system and so we need to
teach the Player assets to appear to the rest of the system that they
are not dead while keeping the nice inherited functionality of sending
a dead event.
Fixes: 07f24fd41857 ("asset manager: check if assets are dead")

AssetManager: prevent removal of Player assets

---

src/dct/assets/Player.lua

To better support multicrew aircraft in the Player class ejection event
handler, only track that an ejection has occurred and do not transition to
the EmptyState until an aircraft crash event occurs or the group no longer
exists. Taking the F-14 as an example this would allow the RIO to eject and
the pilot to still fly the plane and recover the aircraft. For the pilot
death event, just ignore and rely on the plane crash event.
Closes: #169

player: multicrew support

---

.luacheckrc
mission/dct-mission-init.lua

Extend mission environment check to cover 'os' and 'loadlib'.
Closes: #213

mission-init: extend environment check

---

data/DCT/theaters/Caucasus_dctdemo/BlackSea/airbases/CVN71.dct
src/dct/templates/Template.lua

Allows the coalition owner to be specified as either a string or number
in the .dct file. This makes is easier on campaign designers to specify
which side the template should be one without having to remember to
internal numbers DCS specifies.
Closes: #135

template: allow coalition to be a string

---

src/dct/ai/Commander.lua
src/dct/ai/Mission.lua
src/dct/enum.lua
src/dct/ui/cmds.lua
tests/test-ui-cmds.lua

This fixes generation of invalid mode 1 IFF codes, as most aircraft allow 0-7 in the first digit, but only 0-3 the second digit, by moving the mission type (1-5) over to the first digit of the code, and also adds a secondary secondary digit to the generated code, so different mission types of the same kind (ie. Strike, BAI, Armed Recon, CAS) have unique mode 1 codes (50, 51, 52, 53).
This also makes so that assets assigned to mission each get an unique (sequential) mode 3 IFF code, wrapping when the last digit reaches the maximum value (7), to not collide with other mission codes. This will hopefully make cooperation with LotATC-based controllers easier if people follow the mission instructions.
All the new settings are now in the enum.lua file, easily editable alongside other mission …

IFF code generation overhaul

---

data/DCT/theaters/Caucasus_dctdemo/Novorossiysk/misc/NovoStolenAPCs.dct
data/DCT/theaters/Caucasus_dctdemo/Novorossiysk/misc/NovoStolenAPCs.stm
doc/03-designer.md
src/dct/templates/STM.lua
src/dct/templates/Template.lua
tests/test-init.lua
tests/test-theater.lua
tests/test-ui-cmds.lua

This allows a template to contain groups of more than one, on the condition that it is specified in the template's .dct. This can be useful for things such as adding friendly JTACs that are linked to a specific conflict, TACAN navigation beacons, or even friendly troops that can be transported to an objective (via the game's built-in unit transport system).
If the template doesn't have any targets specified, goals will only be auto-generated for objects that belong to the same coalition as the template, but the mission designer is free to explicitly mark neutral or even friendly units as targets (if they find an use case for it).
This also fixes #135 by removing the type requirement from the `coalition` key in templates. The validation method still checks that the input is valid, either …

 Add support for templates with mixed coalitions

---

src/dcttestlibs/dcsstubs.lua

This replicates an anti-pattern of DCS of writing back IDs to the spawn data table to the DCS stubs. Currently, that does not cause any bugs, as the spawn data is deep-copied before use, so tests will pass, but if the deep copy is removed later, such as to re-use IDs when an asset is de-spawned and later spawned again, there needs to be special treatment to not save any runtime IDs when marshaling assets, so this change makes tests fail if the treatment is incomplete.

Add object ID writeback on spawn

---

.luacheckrc
src/dct/libs/Marshallable.lua
src/dct/systems/tickets.lua
src/dct/templates/Template.lua
src/dct/templates/checkers/Check.lua
src/dcttestlibs/dcsstubs.lua

With the ability to call the same set of functions the mission editor can call we are able to eliminate the need for campaign designers to setup end mission triggered on flags.

tickets: remove need to setup end mission triggers
